import Head from "next/head";
import Image from "next/image";
import Main from "@/components/Main";
import About from "@/components/About";
import { Inter } from "next/font/google";
// import styles from '@/styles/Home.module.css'
import Navbar from "../components/Navbar";
import Skills from "../components/Skills";
import AboutImg from "../public/assets/bg_2.jpg";
import Projects from "@/components/Projects";
// import Image from 'next/image';
// import Projects from '../components/Projects'
// import Skills from '../components/Skills'
import Contact from "@/components/Contact";
export default function Home() {
  return (
    <>
      <Head>
        <title>Moaaz | Data Scientist and Web Deveoper</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <div style={{ position: "relative" }}> */}
        {/* <Image
          src={AboutImg}
          layout="fill"
          fill = "fill"
          objectFit="cover"
          quality={100}
          className="absolute inset-0 z-[-1] h-200vh w-full"
        /> */}
        <div style={{ position: "relative", zIndex: "1" }}>
          <Navbar />
          <Main />
          <About />
          <Skills />
          <Projects/>
    <Contact />
        </div>
      {/* </div> */}
    </>
  );
}
